name: Build macOS APP

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build app
        run: |
          chmod +x build_mac.sh
          ./build_mac.sh

      - name: Zip app
        run: ditto -c -k --sequesterRsrc --keepParent "dist/ERNI Stream Downloader.app" "ERNI Stream Downloader macOS.zip"

      - name: Upload macOS APP
        uses: actions/upload-artifact@v4
        with:
          name: ERNI-Stream-Downloader-macOS
          path: ERNI Stream Downloader macOS.zip
